import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/Footer";
import MainHeader from "@/components/MainHeader";
import Layout from "@/components/Layout";
import { Toaster } from "react-hot-toast";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Home | Amazon Clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Layout>
          <MainHeader />
          {children}
          <Footer />
          <Toaster
            position="top-right"
            reverseOrder={false}
          />
        </Layout>
      </body>
    </html>
  );
}
